name: Bug Report
description: Report a bug or issue
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
  - type: textarea
    id: logs
    attributes:
      label: Error messages / logs
      render: shell
