name: Question
description: Ask a question about the project
title: "question: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
